name: Calculator CI

on: [push]

jobs:
  test-calculator:
    name: Test Calulator
    runs-on: ubuntu-latest

    steps:
      - name: üì• –ó–∞–≥—Ä—É–∂–∞–µ–º –∫–æ–¥
        uses: actions/checkout@v3

      - name: üêò –ù–∞—Å—Ç—Ä–∞–∏–≤–∞–µ–º PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: üì¶ –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–µ–π Composer
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: üîç –ü—Ä–æ–≤–µ—Ä–∫–∞ –∫–∞—á–µ—Å—Ç–≤–∞ –∫–æ–¥–∞ (PHPStan)
        run: vendor/bin/phpstan analyse src/ --level=9

      - name: üß™ –ó–∞–ø—É—Å–∫–∞–µ–º —Ç–µ—Å—Ç—ã –∫–∞–ª—å–∫—É–ª—è—Ç–æ—Ä–∞
        run: php tests/CalculatorTest.php
