name: Calculator CI

on: [push]

jobs:
  test-calculator:
    name: Test Calulator
    runs-on: ubuntu-latest

    steps:
      - name: üì• –ó–∞–≥—Ä—É–∂–∞–µ–º –∫–æ–¥
        uses: actions/checkout@v3

      - name: üêò –ù–∞—Å—Ç—Ä–∞–∏–≤–∞–µ–º PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: üß™ –ó–∞–ø—É—Å–∫–∞–µ–º —Ç–µ—Å—Ç—ã –∫–∞–ª—å–∫—É–ª—è—Ç–æ—Ä–∞
        run: php tests/CalculatorTest.php
