name: Calculator CI

on: [push]

jobs:
  name: Test Calulator

  runs-on: ubuntu-latest

  steps:
    - name: ğŸ“¥ Ğ—Ğ°Ğ³Ñ€ÑƒĞ¶Ğ°ĞµĞ¼ ĞºĞ¾Ğ´
      uses: actions/checkout@v3

    - name: ğŸ˜ ĞĞ°ÑÑ‚Ñ€Ğ°Ğ¸Ğ²Ğ°ĞµĞ¼ PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: ğŸ§ª Ğ—Ğ°Ğ¿ÑƒÑĞºĞ°ĞµĞ¼ Ñ‚ĞµÑÑ‚Ñ‹ ĞºĞ°Ğ»ÑŒĞºÑƒĞ»ÑÑ‚Ğ¾Ñ€Ğ°
      run: php tests/CalculatorTest.php
